'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { AlertIcon, CloseIcon, FileIcon, FileUpIcon, InfoIcon, LockIcon, ShieldCheckIcon, SpinnerIcon, UploadIcon, UserSessionIcon } from '@/features/shared/icons';
import { api, getSession, shortId, type Session } from '@/features/shared/api';
import { CertificateArt } from '@/features/shared/CertificateArt';
import { ResultPanel } from './ResultPanel';
import { isRunning, type VerificationJob } from './types';
import { uploadDocument } from './upload';
import type { RecordVerificationResult } from '@verifikasi/domain';
import { recordStatuses } from '@/features/credentials/record-status';

export function VerificationWorkspace({credentialId}:{credentialId?:string}) {
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState('');
  const [job,setJob]=useState<VerificationJob|null>(null); const [error,setError]=useState('');
  const [busy,setBusy]=useState(false); const [dragging,setDragging]=useState(false);
  const [session,setSession]=useState<Session|null>(null); const [demo,setDemo]=useState('match');
  const [record,setRecord]=useState<RecordVerificationResult|null>(null);
  const input=useRef<HTMLInputElement>(null); const requestKey=useRef<string>(''); const lock=useRef(false);
  useEffect(()=>{getSession().then(setSession).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!credentialId)return;const controller=new AbortController();setRecord(null);api<RecordVerificationResult>(`/api/credentials/${encodeURIComponent(credentialId)}/verification`,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setRecord(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[credentialId]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  useEffect(()=>{if(!job || !isRunning(job.status))return;let active=true;let timer:ReturnType<typeof setTimeout>; const poll=async()=>{try{const next=await api<VerificationJob>(`/api/verifications/${job.id}`);if(active){setJob(next);if(isRunning(next.status))timer=setTimeout(poll,1800);}}catch(e){if(active){setError(e instanceof Error?e.message:'Status belum dapat diperbarui.');timer=setTimeout(poll,5000);}}};timer=setTimeout(poll,1200);return()=>{active=false;clearTimeout(timer);};},[job?.id,job?.status]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('job');if(id)api<VerificationJob>(`/api/verifications/${encodeURIComponent(id)}`).then(setJob).catch(e=>setError(e.message));},[]);
  const running=!!job&&isRunning(job.status);
  function choose(files:FileList|File[]|null){if(!files?.length)return;if(files.length!==1){setError('Pilih satu dokumen untuk setiap pemeriksaan.');return;}const selected=files[0];if(!['application/pdf','image/jpeg','image/png'].includes(selected.type)){setError('Format tidak didukung. Gunakan PDF, JPG, atau PNG.');return;}if(selected.size>10*1024*1024){setError('Ukuran berkas melebihi 10 MiB. Pilih berkas yang lebih kecil.');return;}if(!selected.size){setError('Berkas kosong. Pilih dokumen lain.');return;}setFile(selected);setJob(null);setError('');requestKey.current=crypto.randomUUID();}
  async function submit(){if(!file||lock.current)return;lock.current=true;setBusy(true);setError('');try{requestKey.current||=crypto.randomUUID();setJob(await uploadDocument(file,requestKey.current,credentialId));}catch(e){setError(e instanceof Error?e.message:'Dokumen gagal diunggah.');}finally{lock.current=false;setBusy(false);}}
  async function remove(){setError('');try{if(job)await api(`/api/verifications/${job.id}`,{method:'DELETE'});setFile(null);setJob(null);requestKey.current='';if(input.current)input.current.value='';}catch(e){setError(e instanceof Error?e.message:'Dokumen belum dapat dihapus.');}}
  async function showDemo(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await api<VerificationJob>('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:demo})});setFile(null);setJob(result);}catch(e){setError(e instanceof Error?e.message:'Contoh tidak tersedia.');}finally{setBusy(false);lock.current=false;}}
  return <><div className="page-heading verification-heading"><div><h1>Verifikasi Ijazah</h1><p>Cocokkan dokumen Anda dengan rekaman resmi penerbit.</p></div><CertificateArt/></div>
    <nav className="tabs" aria-label="Verifikasi"><Link href="/verifikasi" className="active" aria-current="page">Unggah Dokumen</Link><Link href="/riwayat">Riwayat Verifikasi</Link></nav>
    {credentialId&&<div className="record-notice"><InfoIcon size={19}/><div><strong>Pemeriksaan tambahan untuk rekaman {shortId(credentialId)}</strong><p>{record?`${recordStatuses[record.recordVerificationStatus].label}. `:''}Unggah dokumen yang memuat QR ini untuk mencocokkan atributnya. <Link href={`/c/${encodeURIComponent(credentialId)}`} style={{textDecoration:'underline'}}>Kembali ke rekaman</Link></p></div></div>}
    {error&&<div className="error-message" role="alert"><AlertIcon size={18}/><span>{error}</span><button className="icon-button" aria-label="Tutup pesan" onClick={()=>setError('')}><CloseIcon size={17}/></button></div>}
    <div className="verification-grid"><section className="panel upload-panel" aria-labelledby="upload-title"><h2 id="upload-title">Dokumen Anda</h2>
      <div className={`dropzone ${dragging?'dragging':''} ${file?'has-file':''}`} onDragOver={e=>{e.preventDefault();if(!running)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!running)choose(e.dataTransfer.files);}}>
        <div className="upload-icon"><UploadIcon size={27}/></div><strong>Unggah PDF atau foto ijazah</strong><span>Tarik berkas ke sini, atau pilih dari perangkat</span><button className="button secondary choose-file" disabled={busy||running} onClick={()=>input.current?.click()}>Pilih berkas</button><span className="file-limit">PDF, JPG, atau PNG · Maks. 10 MiB · 5 halaman</span><input className="visually-hidden" ref={input} type="file" accept="application/pdf,image/jpeg,image/png" aria-label="Pilih berkas ijazah" tabIndex={-1} onChange={e=>choose(e.target.files)}/>
      </div>
      {file?<><div className="file-item"><FileIcon size={23} className="file-red"/><div><strong>{file.name}</strong><span>{(file.size/1024/1024).toLocaleString('id-ID',{maximumFractionDigits:2})} MiB</span></div><button className="icon-button" aria-label="Hapus dokumen" onClick={remove}><CloseIcon size={18}/></button></div><div className="preview"><span>Pratinjau dokumen</span>{file.type==='application/pdf'?<object data={preview || undefined} type="application/pdf" aria-label="Pratinjau PDF"><p>Pratinjau PDF tidak tersedia di perangkat ini. Dokumen tetap dapat diperiksa.</p></object>:<img src={preview || undefined} alt="Pratinjau ijazah yang dipilih"/>}</div></>:job?.synthetic?<div className="synthetic-document"><FileIcon size={33}/><strong>Ijazah sintetis</strong><p>Universitas Contoh<br/>Andi Pratama · Informatika</p><span>Hanya untuk demonstrasi tampilan</span></div>:<div className="upload-checklist"><h3>Untuk hasil pembacaan yang baik</h3><p><ChecklistIcon/>Seluruh halaman terlihat dan tidak terpotong</p><p><ChecklistIcon/>Teks tajam, terang, dan mudah dibaca</p><p><ChecklistIcon/>QR dan atribut berada di halaman yang sama</p></div>}
      <div className="upload-actions"><button className="button primary" disabled={!file||busy||running} onClick={submit}>{busy||running?<SpinnerIcon size={17} className="spin"/>:<ShieldCheckIcon size={17}/>} {running?'Sedang memproses':'Verifikasi Dokumen'}</button>{file&&<button className="button secondary" disabled={busy||running} onClick={()=>input.current?.click()}>Ganti dokumen</button>}</div>
      <div className="upload-privacy"><LockIcon size={15}/><p>Dokumen unggahan diproses oleh server untuk pembacaan OCR. Akses berkas berakhir 1 jam setelah proses selesai, paling lambat 24 jam sejak unggah. Penghapusan berkas berjalan terjadwal dan dapat tertunda saat layanan terganggu.</p></div>
    </section><ResultPanel job={job} onRetry={async()=>{if(job&&!job.synthetic){try{setJob(await api<VerificationJob>(`/api/verifications/${job.id}/retry`,{method:'POST'}));}catch(e){setError(e instanceof Error?e.message:'Coba unggah kembali.');}}else await showDemo();}}/></div>
    <div className="under-workspace"><div><InfoIcon size={17}/><span>Baru pertama kali memeriksa ijazah? <Link href="/panduan">Baca panduan verifikasi</Link></span></div><span><UserSessionIcon size={15}/>Tanpa akun atau wallet</span></div>
    {session?.mode==='demo'&&<details className="demo-tools"><summary>Mode demo lokal · Jelajahi contoh hasil</summary><div><p>Unggahan memerlukan worker OCR. Contoh berikut memakai data sintetis dan tidak menjalankan transaksi FHE.</p><label htmlFor="demo-scenario">Contoh hasil</label><select id="demo-scenario" value={demo} onChange={e=>setDemo(e.target.value)}><option value="match">Atribut cocok</option><option value="mismatch">Ketidaksesuaian atribut</option><option value="revoked">Kredensial dicabut</option><option value="not_found">Rekaman tidak ditemukan</option><option value="inconclusive">OCR belum memadai</option><option value="error">Layanan terganggu</option></select><button className="button secondary" onClick={showDemo} disabled={busy||running}>Tampilkan contoh</button></div></details>}
  </>;
}
function ChecklistIcon(){return <span className="check-outline"><FileUpIcon size={13}/></span>;}
